language: go
go:
    - 1.3.1
    - 1.3.2
    - 1.3.3

install:
    - go get -v -t ./...
    - go get code.google.com/p/go.tools/cmd/cover
    - go get github.com/onsi/gomega
    - go install github.com/onsi/ginkgo/ginkgo
    - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --cover --trace --race